### ISSUE TITLE
[nugets_pack] Support nuget gen for configure .Net version

### ISSUE THREAD

**Issue by haf** [Albacore/albacore#148]
This issue tracks generation of nugets with correct versions from their xxproj-files respective `TargetFrameworkVersion` elements.

Usages:

```
$ grep -R --include '*.rb' net40 lib
lib/albacore/nuget_model.rb:            dotnet_version:       'net40',
lib/albacore/project.rb:                           :target_framework => 'net40',
lib/albacore/task_types/nugets_pack.rb:      # the .net target (e.g. net40, mono20, mono3, etc)
lib/albacore/task_types/nugets_pack.rb:        @target  = 'net40'
```

**Comment by danieljsummers** [comment]
I'm guessing this isn't as simple as adding `p.target = 'net452'` (for example) to the example block in the comment block [here](https://github.com/Albacore/albacore/blob/master/lib/albacore/task_types/nugets_pack.rb#L108)?  Or, does it need a separate def like `mono_opt_out` that would allow it to be set?  And, if it's the latter, would you want it to just take a string, or would you want it to enumerate and validate all the possible values that could be selected?

**Comment by haf** [comment]
It is that simple to override the default; so you can PR that to the dependent projects, but this issue is about detecting the framework by reading `TargetFrameworkVersion` from the xxproj file. Read it, set it to the config, done.

**Comment by danieljsummers** [comment]
I forked and [wrote some code](https://github.com/danieljsummers/albacore/tree/feature/148-fx-detection) that seems to address it with the tests I have.  Do you want to review it before I submit a PR, or do you want me to go ahead and submit it?

The way I implemented it, if "target" isn't set, I set it based on the xxproj file; if it is, I leave it alone.  That gives people a way to override it.  I also changed the default value to '', so I could tell if it had been set or not.

**Comment by haf** [comment]
That code looks great, hand over the PR ;)
