### ISSUE TITLE
[build] Writes unnecessary INFO message when looking for msbuild (windows)

### ISSUE THREAD

**Issue by joelwilson** [Albacore/albacore#153]
When executing the build task, Albacore calls `CrossPlatformCmd.which` a few times in an effort to find the correct build tool. See [build.rb:44](https://github.com/Albacore/albacore/blob/6f662bf78a72ff7314c02049f23f8d86c268b1d7/lib/albacore/task_types/build.rb#L44)

On Windows 7, the non-matching calls results in `where` being called a few times. When `where` can't find the command, it returns an informational message, which Albacore does not suppress, revealing some of the internal goings-on of Albacore to the user. In my case, there were four messages:

    INFO: Could not find files for the given pattern(s).
    INFO: Could not find files for the given pattern(s).
    INFO: Could not find files for the given pattern(s).
    INFO: Could not find files for the given pattern(s).

The nanoc repo has a [pull request (298)](https://github.com/nanoc/nanoc/pull/298) containing a solution to this problem. Simply use `command 2> nul` to [redirect error messages](http://support.microsoft.com/kb/110930) on Windows. That would require some changes to [cross_platform_cmd.rb:186](https://github.com/Albacore/albacore/blob/eddc4be9032738288dc84e0b332855639b801eca/lib/albacore/cross_platform_cmd.rb#L186).

**Comment by haf** [comment]
Go ahead, I'll merge the PR ;)

**Comment by haf** [comment]
I've pushed a new albacore release.
