### ISSUE TITLE
Mono runtime

### ISSUE THREAD

**Issue by wallymathieu** [Albacore/albacore#158]
When running nunit I have the problem that mono runs it as .net 2. Thus stuff that works when running 

```
mono --runtime=v4.0.30319 #{nunit_cmd} #{some_dll}
````

does not work when running

```ruby
desc "test using console"
test_runner :test => [:build] do |runner|
  runner.exe = NugetHelper.nunit_path
  files = Dir.glob(File.join($dir,"*Tests","bin","**","*Tests.dll"))
  runner.files = files 
end
```

**Comment by wallymathieu** [comment]
Perhaps easiest to use some other solution. I looked at the code, and it might get a bit complicated by adding runtime to mono prefix.

**Comment by haf** [comment]
I'd be open for a rewrite of the nunit task type, so if you want it another way, then go ahead. I'm not using it myself and it's responsible for the bugs in the issue tracker.

**Comment by wallymathieu** [comment]
Well, it works well enough for my needs.
