### ISSUE TITLE
Help or Advice

### ISSUE THREAD

**Issue by dsphillips87** [Albacore/albacore#159]
I am trying to use albacore to automate creation of NuGet packages. I'm testing with a simple HelloWorld application. However it doesn't seem to be picking up the assembly info for the project. The author and description have the value "MISSING".

I can build the packages as normal using NuGet.exe with a nuspec file with placeholders $author$, $description$ but I cannot get it working with rake and albacore. Apologies if this is something simple I'm missing but I have looked at the code and can't work it out.

I've attached the log output, RakeFile and the nuspec file it creates. It hasn't got any of my assemblyinfo content in it.

Any help would be appreciated. Thanks.

![rakefile](https://cloud.githubusercontent.com/assets/11577539/6759547/b4ed7f0e-cf38-11e4-8f1a-d8f4efcaad09.png)
![logoutput](https://cloud.githubusercontent.com/assets/11577539/6759545/b4e9f28a-cf38-11e4-9833-a64f4f07bc47.png)
![nuspec file generated by albacore](https://cloud.githubusercontent.com/assets/11577539/6759546/b4ec936e-cf38-11e4-920e-036f44d9fd5f.png)

**Comment by haf** [comment]
Do

```
p.with_metadata do |p|
  p.authors = "...."
  # etc
end

**Comment by haf** [comment]
Also, I recommend that you put the side-effecting operations in their own task and make a dependency relationship:

```
nugets_pack :pack => [:prepare] do |p|
  # only config in here
end

task :afterwards => :pack do
  FileUtils ...
end

**Comment by dsphillips87** [comment]
Thanks for the feedback. I will separate the file utils call as you sugested. However with the metadata I am trying to read the authors and description from the assembly info included by each of the .csproj files. So I can have individual descriptions for each package. Does that make sense?

**Comment by dsphillips87** [comment]
Just thinking do I need to write my own nuspec file if I want to do it that way?

**Comment by haf** [comment]
You can either generate the assembly version info through the asmver task type, or you can edit each corresponding `<Author ...` etc tag inside the csproj file or you can use the object model to generate the nuspec file, or you can alternatively write your own nuspec file.

The workflow in albacore is optimised for using the asmver and amsver_files task types - less friction, all stuff inside the Rakefile.

**Comment by haf** [comment]
Closing, if you have further queries, just ask!
