### ISSUE TITLE
Add ILMerge as tool

### ISSUE THREAD

**Issue by devployment** [Albacore/albacore#164]
As just discussed in [Gitter](https://gitter.im/Albacore/albacore?at=55658004dacb05b3394a0edb) we can add support for ILMerge as tool.

**Comment by wallymathieu** [comment]
But, isnt the problem with ILMerge its license?

**Comment by haf** [comment]
We'd just be adding logic around invoking it properly, not the actual binary.

**Comment by wallymathieu** [comment]
Do you have any luck using any open source alternative like https://github.com/gluck/il-repack ?

**Comment by haf** [comment]
https://github.com/gluck/il-repack/issues/68

**Comment by devployment** [comment]
For now I gave up on the merge topic in my current project. I had a lot of issues packing the library. But I'll probably try it again later. Will get back to add it to Albacore then again.

**Comment by haf** [comment]
I wish compiler authors would provide this as an opt-in feature rather than relying on IL-tools. What would be the outlook for such an outcome, @enricosada ?

**Comment by wallymathieu** [comment]
I used some script to clear and add references to files from one project to another in order to avoid problems of ILMerge messing up my dll's.

**Comment by haf** [comment]
Yeah, I have the same in place with my [YoLo.fs](https://github.com/haf/YoLo/blob/master/YoLo.fs)

**Comment by haf** [comment]
Closing due to lack of action.
