### ISSUE TITLE
Doesn't work with MSBuild 14.0

### ISSUE THREAD

**Issue by aaronasmith** [Albacore/albacore#170]
It looks like there's an array that starts at 12.0 and goes down from there in the build.rb file.  Does that array need to have 14.0 added to it in order to build for C# 6.0?

**Comment by haf** [comment]
Yes

**Comment by aaronasmith** [comment]
I was going to attempt to change it and do a pull request, but I can't get wdm to install on my machine.  Couldn't you just inspect the HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\MSBuild\ToolsVersions for all of the versions installed, pick the greatest one and use that?  Then you wouldn't need an update for every new tools version that comes out.

**Comment by haf** [comment]
What's WDM?

I believe that's [being inspected](https://github.com/Albacore/albacore/blob/master/lib/albacore/task_types/build.rb#L185-L204).

The build task-type is completely PR-maintained nowadays as I've migrated 100% to OS X and Linux and mono. I'm still using albacore for everything though ;) If you think inspecting that key gets you the best version number, go for it and PR :)

**Comment by aaronasmith** [comment]
I have no idea what wdm is.  It shows up as an error when I'm trying to do bundle install.  So I take it this won't be fixed unless there is a PR?

**Comment by haf** [comment]
Well, I can probably help you with WDM if you'd post error messages, but no, I'm not going to fix it, because I don't have a Windows machine to reproduce the error on and VS2015 takes three hours just to install according to reliable twitteratis.

**Comment by aaronasmith** [comment]
Here's the error message when I do a bundle install.  I could do a pull request with untested code, but I don't think that's a good idea, especially since I'm not all that great with ruby.

    bundle install
    Fetching gem metadata from https://rubygems.org/.........
    Fetching version metadata from https://rubygems.org/..
    Resolving dependencies...
    Using rake 10.4.2
    Using map 6.5.5
    Using mini_portile 0.6.2
    Using nokogiri 1.6.6.2
    Using semver2 3.4.2
    Using albacore 2.4.3 from source at .
    Using diff-lcs 1.2.5
    Using rspec-support 3.3.0
    Using rspec-core 3.3.2
    Using rspec-expectations 3.3.1
    Using rspec-mocks 3.3.2
    Using rspec 3.3.0
    Using rubygems-tasks 0.2.4
    Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

        C:/tools/ruby193/bin/ruby.exe -r ./siteconf20150728-14972-1mk0yo0.rb extconf.rb
    checking for main() in -lkernel32... yes
    checking for windows.h... yes
    checking for ruby.h... yes
    checking for HAVE_RUBY_ENCODING_H... yes
    checking for rb_thread_call_without_gvl()... yes
    creating Makefile
    
    make  clean
    Makefile:165: *** target pattern contains no `%'.  Stop.
    
    make
    Makefile:165: *** target pattern contains no `%'.  Stop.
    
    make failed, exit code 2
    
    Gem files will remain installed in C:/tools/ruby193/lib/ruby/gems/1.9.1/gems/wdm-0.1.1 for inspection.
    Results logged to C:/tools/ruby193/lib/ruby/gems/1.9.1/extensions/x86-mingw32/1.9.1/wdm-0.1.1/gem_make.out
    An error occurred while installing wdm (0.1.1), and Bundler cannot continue.
    Make sure that `gem install wdm -v '0.1.1'` succeeds before bundling.

**Comment by haf** [comment]
So here's the thread in the wdm library that discusses the issue.

https://github.com/Maher4Ever/wdm/issues/18

The reason you're having trouble is that you're on a too-old version of ruby, mate.
