### ISSUE TITLE
MS test wont run with Albacore 2.5

### ISSUE THREAD

**Issue by shine17** [Albacore/albacore#178]
Below is the test_runner code - 

test_runner :tests do |tests|
  tests.files = FileList['C:\GitRepos\shinetest\testapps\Albacorerakesample\AlbacoreRakeDotnetBuildSample\AlbacoreRakeDotnetBuildSample.Tests\bin\Release\AlbacoreRakeDotnetBuildSample.Tests.dll'] 
  tests.exe = 'C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\MSTest.exe'
  tests.native_exe
end

The error am getting is 
Invalid switch "albacorerakedotnetbuildsample.tests.dll".
Below is the trace -

Invalid switch "albacorerakedotnetbuildsample.tests.dll".
For switch syntax, type "MSTest /help"
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/albacore-2.5.1/lib/albacore/cross_platform_cmd.rb:263:in `raise_failur
e'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/albacore-2.5.1/lib/albacore/cross_platform_cmd.rb:242:in `block in han
dler_with_message'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/albacore-2.5.1/lib/albacore/cross_platform_cmd.rb:111:in `call'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/albacore-2.5.1/lib/albacore/cross_platform_cmd.rb:111:in `block in sys
tem'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/albacore-2.5.1/lib/albacore/cross_platform_cmd.rb:247:in `handle_not_f
ound'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/albacore-2.5.1/lib/albacore/cross_platform_cmd.rb:87:in `system'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/albacore-2.5.1/lib/albacore/task_types/test_runner.rb:73:in `execute'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/albacore-2.5.1/lib/albacore/task_types/test_runner.rb:104:in `block in
 execute_tests_for'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/albacore-2.5.1/lib/albacore/task_types/test_runner.rb:138:in `handle_d
irectory'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/albacore-2.5.1/lib/albacore/task_types/test_runner.rb:98:in `execute_t
ests_for'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/albacore-2.5.1/lib/albacore/task_types/test_runner.rb:92:in `block in
execute'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/file_list.rb:81:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/file_list.rb:81:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/albacore-2.5.1/lib/albacore/task_types/test_runner.rb:90:in `execute'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/albacore-2.5.1/lib/albacore/dsl.rb:82:in `block in test_runner'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
C:/opscode/chef/embedded/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_le
vel'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handlin
g'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
C:/opscode/chef/embedded/bin/rake:23:in `load'
C:/opscode/chef/embedded/bin/rake:23:in `<main>'
Tasks: TOP => tests

**Comment by haf** [comment]
Hi, this is a known issue, but noone has wanted to fix it.

https://github.com/Albacore/albacore/issues/125 was where we discussed it...

**Comment by shine17** [comment]
Thanks. I change it to Nunit and it worked

**Comment by andyfenna** [comment]
will this ever get fixed?

**Comment by haf** [comment]
@andyfenna Only ever through pull requests. Feel free to fix it.

**Comment by andyfenna** [comment]
I've fixed it, needs testing etc, i'll do a pull request now ;)
