### ISSUE TITLE
Alabcore not building the project in 'Release' mode

### ISSUE THREAD

**Issue by shine17** [Albacore/albacore#179]
desc "Run a simple clean and rebuild"
build :buildSln  do |msb|
  msb.sln = 'C:\GitRepos\shinetest\testapps\Albacorerakesample\AlbacoreRakeDotnetBuildSample\AlbacoreRakeDotnetBuildSample.sln' #Path of solution file.
  msb.target = [:Clean, :Rebuild]  
  msb.properties = {
                     :Configuration => 'Release' ,
                    :Platform => 'Any CPU',
                    :verbosity  => 'detailed',     
                    }
  msb.logging = 'detailed'  
  msb.clp 'ShowEventId'    
end

Its always building dll under Debug folder. No release folder created and no dll with Release mode.
Please help ! Thanks in advance !

**Comment by haf** [comment]
Please have a look at the docs https://github.com/Albacore/albacore/wiki/build for the build task and copy how it's done there.
