### ISSUE TITLE
Problem building projects using MSBuild 14

### ISSUE THREAD

**Issue by wallymathieu** [Albacore/albacore#184]
When building a project that uses c# 6 features we had some trouble due to the msbuild version chosen by albacore to be msbuild 12. This could be due to the new location of msbuild 14. 
```C:\Program Files (x86)\MSBuild\14.0\Bin\Msbuild```

**Comment by haf** [comment]
@wallymathieu This should have been solved by https://github.com/Albacore/albacore/pull/171 – could you contact the people in that thread, please?

**Comment by wallymathieu** [comment]
It looks like two problems:
- When the registry keys are unordered, the algorithm used picks the wrong one (see #185 ).
- When using github for windows it looks like I've got msbuld 12 in path, so then it uses that one.

**Comment by haf** [comment]
I see; you should change your path imo; that's the gold standard for finding things. But your PR solved the first issue, and that's good!

**Comment by wallymathieu** [comment]
I agree, probably it's due the shell pulling in more things in path than it should.

**Comment by wallymathieu** [comment]
I've sent github a notice about the issue with their tool

**Comment by wallymathieu** [comment]
Lets close this issue, since it's not related to albacore anyway.
