### ISSUE TITLE
nugets_pack with nuget_gem_exe path problem

### ISSUE THREAD

**Issue by joelwilson** [Albacore/albacore#186]
I tried to use the nuget gem today when creating a `nugets_pack` task. It turns out that albacore improperly constructs the path to `nuget.exe`:

```
Errno::EINVAL: Invalid argument - c:\Users\jwilson\Code\MediaManager\c:\opscode\chefdk\embedded\lib\ruby\gems\2.1.0\gems\nuget-2.8.60717.93\bin\nuget.exe
```

The problem appears to be that the [path_to](https://github.com/Albacore/albacore/blob/6b836a867f6cce6de312c02ff8e4841e3463ae19/lib/albacore/task_types/nugets_pack.rb#L244) method is written to handle relative paths only. However, the [find_nuget_gem_exe](https://github.com/Albacore/albacore/blob/6b836a867f6cce6de312c02ff8e4841e3463ae19/lib/albacore/task_types/nugets.rb#L1-L8) method returns the absolute path to the executable.

At least, this is my experience on  Windows.

**Comment by haf** [comment]
/cc @wallymathieu 

We should change `path_to` to only expand relative paths.

**Comment by wallymathieu** [comment]
Perhaps something like
```ruby
require 'pathname'
...
      def path_to path, cwd
        if (Pathname.new path).absolute?
           return path
        else
           File.expand_path( File.join(@opts.get(:original_path), path), cwd )
       end
```
?

**Comment by haf** [comment]
Sounds like a good solution! @joelwilson – do you want to do the honours?

**Comment by joelwilson** [comment]
I can try out the fix but not until I get back to a Windows machine on
Monday.

**Comment by haf** [comment]
No rush :). Try it out Monday and send a PR then.

**Comment by wallymathieu** [comment]
Sounds good!

**Comment by haf** [comment]
@joelwilson Any progress on this :)?

**Comment by joelwilson** [comment]
@haf sorry I haven't been working with ruby or albacore in a while. Does someone else want to make this change?

**Comment by haf** [comment]
I think you were onto something with the specific gems for paket and/or nuget.

**Comment by VoX** [comment]
This is still pretty annoying if you just want to run nuget.exe as found in the path. 

```
This works as expected 
nugets_restore :nuget_restore => [:check_nuget] do |p|
	p.out = 'packages'
	p.exe = 'nuget.exe'
end
```

This concats the executable name to the working directory causing it to fail
```
nugets_pack :pack do |p|
	p.files   = 'project.csproj'
	p.out     = 'build'
	p.exe = 'nuget.exe'
end
```

Albacore::CommandNotFoundError: Command failed with status (127) - number 127 in particular means that the operating system could not find the executable:
  C:\dev\project\nuget.exe

**Comment by wallymathieu** [comment]
So it would be nice to normalise the behaviour.

**Comment by wallymathieu** [comment]
@haf what's the status on this one? The path_to logic should perhaps be moved to "paths.rb" and amended with http://stackoverflow.com/questions/2108727/which-in-ruby-checking-if-program-exists-in-path-from-ruby ?

**Comment by haf** [comment]
It should use the PATH. Good catch.

**Comment by haf** [comment]
Ping; what's the consensus? We should default to PATH and then go towards folder-local files?

**Comment by haf** [comment]
Timed out.
