### ISSUE TITLE
Engine is nil error with asmver_files method

### ISSUE THREAD

**Issue by munnster** [Albacore/albacore#188]
Hi when using the asmver_files method I get the following error

    rake aborted!
    ArgumentError: engine is nil
    C:/Ruby200/lib/ruby/gems/2.0.0/gems/albacore-2.5.4/lib/albacore/task_types/asmver/file_generator.rb:15:in `initialize'

This is my task in my rake script. Not really sure what I'm missing here.

     desc 'Update version numbers'
     asmver_files :versions do |a|
       a.files = FileList['**/Properties/AssemblyVersionInfo.cs']
       a.attributes assembly_version: solution_version,
                    assembly_file_version: solution_version,
                    assembly_description: 'Build: #{build_version}'
     
       a.handle_config do |proj,conf|
         conf 
       end 
     end 

Thanks 

Ali

**Comment by haf** [comment]
`files` is a file list of the `csproj` files, not of your assembly version info files.

**Comment by haf** [comment]
Not a bug.
