### ISSUE TITLE
How to stop overwriting existing nuspec file?

### ISSUE THREAD

**Issue by AMoghrabi** [Albacore/albacore#196]
I am following the example on the wiki on how to build a nuget package. I want it to build using an existing nuspec file. However, albacore forcefully overwrites the existing nuspec file. I cannot find an option to disable this behavior, even though there was an issue created a few years back to address support for existing nuspec files.

My goal is to use an existing nuspec file if it exists and only modify the author, description, and version. If one does not exist, I would like albacore to generate one.

Thanks for the help.

**Comment by haf** [comment]
We did have an issue a few years back, but that feature fell into disrepair as it didn't have proper unit tests to keep it alive. We can still read a nuspec file but can't avoid overwriting it anymore. If you fix the feature back up that would make a good PR; remember to add PRs.

If you just want to see the generated nuspec, just add DEBUG=true .

**Comment by AMoghrabi** [comment]
Thanks for the quick response. I would love to attempt it but I am not very good with Ruby unfortunately :(

**Comment by haf** [comment]
We all start somewhere...

**Comment by AMoghrabi** [comment]
Good point :) I will strongly consider doing this, actually. It's a good learning opportunity. Thanks @haf.

**Comment by haf** [comment]
Closing due to lack of action. We can re-open if we decide we want this feature.
