### ISSUE TITLE
Releasing nuget packages without using versionizer?

### ISSUE THREAD

**Issue by AMoghrabi** [Albacore/albacore#197]
Is it possible to use the `:release` task without using the versionizer task? We have our scripts configured to pick up the `:build_number` from Team City so the `.semver` file is not necessary to have in our case. I would also like to avoid having to add a dependency (`semver` gem).

Thanks for the help.

**Comment by haf** [comment]
Yes, just override `:depend_on` - https://github.com/Albacore/albacore/blob/master/lib/albacore/tasks/release.rb#L44

The semver gem is my creation, and I can promise you it's semantically versioned and stable ;)
