### ISSUE TITLE
nuspec: Normalizing target results in invalid spec

### ISSUE THREAD

**Issue by et1975** [Albacore/albacore#199]
Nuget seems to require `\` slashes for targets, so [this line](https://github.com/Albacore/albacore/blob/master/lib/albacore/nuget_model.rb#L25) results in "content-only" nuget, and ultimately packaging fails on Linux.

**Comment by haf** [comment]
@et1975 Would you be open to PRing a fix to that?

**Comment by et1975** [comment]
doubtful

**Comment by haf** [comment]
Use paket then.
