### ISSUE TITLE
Reading information from existing AssemblyInfo files

### ISSUE THREAD

**Issue by metatron-the-chronicler** [Albacore/albacore#211]
With Albacore 2 how can I read the information in a pre-existing AssemblyInfo.cs file? I want to use this data as the basis for NuGet packages stemming from a solution with multiple sub-projects.

**Comment by haf** [comment]
I never had any use for that particular functionality; but if you want it, it would make sense to add. Feel free to PR it here :)

**Comment by metatron-the-chronicler** [comment]
Submitted pull request. #214

**Comment by haf** [comment]
Merged PR.

**Comment by haf** [comment]
Could you please document this feature on the wiki, to finish it off and make it releasable?
