### ISSUE TITLE
Unable to activate, rake conflict

### ISSUE THREAD

**Issue by bgblanch** [Albacore/albacore#222]
### Operating System
- Windows 7

### Ruby Version
- 2.3.3 from http://rubyinstaller.org

### Gem List
```bash
*** LOCAL GEMS ***

albacore (2.6.2)
bigdecimal (1.2.8)
did_you_mean (1.0.0)
io-console (0.4.5)
json (1.8.3)
map (6.6.0)
mini_portile2 (2.1.0)
minitest (5.8.5)
net-telnet (0.1.1)
nokogiri (1.6.8.1 x64-mingw32)
power_assert (0.2.6)
psych (2.1.0)
rake (12.0.0, 10.4.2)
rdoc (4.2.1)
semver2 (3.4.2)
test-unit (3.1.5)
```

### Installation
```bash
C:\Users\jon>gem install rake
Fetching: rake-12.0.0.gem (100%)
Successfully installed rake-12.0.0
Parsing documentation for rake-12.0.0
Installing ri documentation for rake-12.0.0
Done installing documentation for rake after 2 seconds
1 gem installed

C:\Users\jon>gem install albacore
Fetching: map-6.6.0.gem (100%)
Successfully installed map-6.6.0
Fetching: mini_portile2-2.1.0.gem (100%)
Successfully installed mini_portile2-2.1.0
Fetching: nokogiri-1.6.8.1-x64-mingw32.gem (100%)
Nokogiri is built with the packaged libraries: libxml2-2.9.4, libxslt-1.1.29, zl
ib-1.2.8, libiconv-1.14.
Successfully installed nokogiri-1.6.8.1-x64-mingw32
Fetching: semver2-3.4.2.gem (100%)
Successfully installed semver2-3.4.2
Fetching: albacore-2.6.2.gem (100%)
Successfully installed albacore-2.6.2
Parsing documentation for map-6.6.0
Installing ri documentation for map-6.6.0
Parsing documentation for mini_portile2-2.1.0
Installing ri documentation for mini_portile2-2.1.0
Parsing documentation for nokogiri-1.6.8.1-x64-mingw32
Installing ri documentation for nokogiri-1.6.8.1-x64-mingw32
Parsing documentation for semver2-3.4.2
Installing ri documentation for semver2-3.4.2
Parsing documentation for albacore-2.6.2
Installing ri documentation for albacore-2.6.2
Done installing documentation for map, mini_portile2, nokogiri, semver2, albacor
e after 16 seconds
5 gems installed
```

### Error Message
```bash
C:\code\edt>rake
rake aborted!
Gem::ConflictError: Unable to activate albacore-2.6.2, because rake-12.0.0 conflicts with rake (~> 10)
C:/code/edt/rakefile:2:in `<top (required)>'
Gem::ConflictError: Unable to activate albacore-2.6.2, because rake-12.0.0 conflicts with rake (~> 10)
C:/code/edt/rakefile:2:in `<top (required)>'
LoadError: cannot load such file -- albacore
C:/code/edt/rakefile:2:in `<top (required)>'
(See full trace by running task with --trace)
```

**Comment by haf** [comment]
Run `bundle exec rake` after installing `bundler`.

**Comment by bgblanch** [comment]
```bash
C:\code\edt>bundle exec rake
Could not locate Gemfile or .bundle/ directory
```

**Comment by bgblanch** [comment]
I get the same thing on my linux box when I run `bundle exec rake`.  I cd'd to my home directory and ran it (there is a .bundle directory there) but it still returned the same error.

**Comment by haf** [comment]
I see. This is because you don't have a gemfile in your project. Add a file like these to your project, run `bundle` and then `bundle exec rake`:

 - https://github.com/SuaveIO/suave/blob/master/Gemfile
 - https://github.com/haf/DVar/blob/master/Gemfile
 - https://github.com/logary/logary/blob/master/Gemfile

**Comment by bgblanch** [comment]
I don't think that's it.  On my linux box `rake` is working fine with no gemfile in the project directory.  I get the same error, however, on the linux box.

**Comment by bgblanch** [comment]
I have a number of Gemfiles due to my vagrant installation but nothing in the project folder.

**Comment by haf** [comment]
I'm saying that you need to add them to the project folder so you can choose the version of rake to bind to.

Otherwise, you can PR this repo with a bumped dependency on rake and I'll release a version that works out of the box without bundler.

**Comment by bgblanch** [comment]
Y:\edt >gem install bundler
Successfully installed bundler-1.13.6
Parsing documentation for bundler-1.13.6
Done installing documentation for bundler after 3 seconds
1 gem installed

Y:\edt >bundle exec rake
Could not locate Gemfile or .bundle/ directory

**Comment by bgblanch** [comment]
I figured it out.  I had to log into the box as Administrator to run the scripts (user was an Administrator but not able to run gem install... or bundle...)
