### ISSUE TITLE
Support for MSBuild 15

### ISSUE THREAD

**Issue by dusk0r** [Albacore/albacore#229]
MSBuild doesn't write a registry key into HKLM\SOFTWARE\Microsoft\MSBuild. On my machine it's installed into the V2017 directory:
%programfiles(x86)%\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin

See
https://github.com/Microsoft/msbuild/issues/1377

**Comment by haf** [comment]
Could you please add and test this heuristic here? https://github.com/Albacore/albacore/blob/master/lib/albacore/task_types/find_msbuild_versions.rb

**Comment by dusk0r** [comment]
Yes. But that path is not fixed, it's just the default installation path. And there are three versions of VS2017 (Community, Professional and Enterprise). Each with a slightly different path.

How should we handle this? Just assume the default installation path?

**Comment by haf** [comment]
You could always put it on path. But yes, list as many paths as you may find to the professional/ultimate/community editions and place them in the heuristic function; it's good enough – if it's not then you could always use the PATH env var.

**Comment by haf** [comment]
Merged PR #230
