### ISSUE TITLE
2.6.6 gem does not contain full path for MSBuild 15

### ISSUE THREAD

**Issue by tran-barry** [Albacore/albacore#232]
Code is correct in repository, but rubygems.org does not contain commit b956861dd3be77c5eae22a27615d1556a433ead0 .

Please release a new gem on rubygems.org

**Comment by aloker** [comment]
Please release an updated version. This is a show stopper for us. We can't require our developers to fix their gems locally.

**Comment by haf** [comment]
Pushed

**Comment by aloker** [comment]
Much appreciated, thanks a lot.

**Comment by haf** [comment]
You're welcome.
