### ISSUE TITLE
Question: Support for .NET Core?

### ISSUE THREAD

**Issue by polarapfel** [Albacore/albacore#233]
Hi,

can anyone share any experience (or caveats) using this with .NET Core?

thanks,

Tobias W.

**Comment by haf** [comment]
Right now it's similar to https://github.com/SuaveIO/suave/blob/master/Rakefile#L183 – there are no specific .Net Core task-types available, but since it's a pretty generic build system it's not hard to call into .Net Core.

**Comment by polarapfel** [comment]
@haf Thanks!
