### ISSUE TITLE
Long run time

### ISSUE THREAD

**Issue by LaraUrban** [Albacore/albacore#244]
I think albacore's run time behaves weird when I increase the read size and the worker threads. I allocate a lot of memory (up to 1TB), and try to run a chunk size of 10kb (--basecaller_max_events=10000) on 41GB of fast5 files with various number of worker threads. Weirdly, 16 worker threads perform much better than 32, and the run time is increasing with an increasing number of worker threads. 
Do you know why this happens? Alternatively, is there another possibility to speed up the base-calling? 
Thank you!

**Comment by haf** [comment]
Sorry, you're in the wrong project.
