### ISSUE TITLE
New maintainer wanted

### ISSUE THREAD

**Issue by jacob-ewald** [Albacore/albacore#252]
I see that #251 was merged, but there's been no release of it on RubyGems. Any chance someone can push a new gem?

**Comment by haf** [comment]
I'd be happy to onboard a new release manager / maintainer.

**Comment by haf** [comment]
PS: alternatively, sponsorships are nice

**Comment by haf** [comment]
Not solved. Reopen.

**Comment by logiclrd** [comment]
Yeah, my change to enable it to find newer MSBuild versions back in 2019 never got released either...
